### ISSUE TITLE
Broken links and spelling error

### ISSUE THREAD

**Issue by samchappel** [learn-co-curriculum/python-p3-final-project#1]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231382?module_item_id=541606

### Concern

Under the Tips and Tricks heading, the last bullet point has two pages linked and both links are broken:
'Consider using [Click](https://learning.flatironschool.com/courses/6258/assignments/click) or [Fire](https://learning.flatironschool.com/courses/6258/assignments/fire) to take care of basic CLI tasks for you.'

The third bullet point also as a spelling error of the world 'will':
If you get stuck trying to accomplish a specific task, check online to see if there's a Python library that wlil make it easier.

**Comment by professor-ben** [comment]
Thanks for reporting these issues! They have been fixed and should be visible in Canvas tomorrow.
